### ISSUE TITLE
Question about portMUX_TYPE use on ESP32_Interrupt_Example.ino

### ISSUE THREAD

**Issue by Rob2029** [G6EJD/ESP_Interrupt_Examples#1]
I want to know if I have to use multiple _portMUX_TYPE_ variables in case I use multiple ISR routines
for example:

`portMUX_TYPE synch1 = portMUX_INITIALIZER_UNLOCKED;
portMUX_TYPE synch2 = portMUX_INITIALIZER_UNLOCKED;

void IRAM_ATTR blink1()
{
  portENTER_CRITICAL(&synch1);
  state = !state;
  portEXIT_CRITICAL(&synch1);
}
void IRAM_ATTR blink2()
{
  portENTER_CRITICAL(&synch2);
  state = !state;
  portEXIT_CRITICAL(&synch2);
}`

Is this correct? Or can I use the same _synch_ variable for multiple ISR functions??

**Comment by G6EJD** [comment]
I think I’ve answered your query, but in this example your modifying the same variable in both routines so I would not be surprised if that created a conflict when both handlers eventually got triggered and then one inevitably had control when the other tried to modify the locked variable it would fail.

**Comment by Rob2029** [comment]
Yes you responded me in Youtube, but I am sorry I meant to have different variables in each ISR. Like this:

`portMUX_TYPE synch1 = portMUX_INITIALIZER_UNLOCKED;
portMUX_TYPE synch2 = portMUX_INITIALIZER_UNLOCKED;

void IRAM_ATTR blink1()
{
portENTER_CRITICAL(&synch1);
state1 = !state1;
portEXIT_CRITICAL(&synch1);
}
void IRAM_ATTR blink2()
{
portENTER_CRITICAL(&synch2);
state2 = !state2;
portEXIT_CRITICAL(&synch2);
}`

**Comment by G6EJD** [comment]
That's looks OK, are you still having issues?

**Comment by Rob2029** [comment]
I have not tried yet because this was for a project i did last december so i have to rig everything up again to try using a portMUX_TYPE variable for each ISR, I hope to try this using 6 water flow sensors (hall effect) that produce a signal with a frecuency less than 900Hz so I think the ESP32 can handle that, I guess if I use signals with higher frecuency I will have problems.
Thanks for you help, as soon as I try the code I'll report if there's an issue. kind regards from Costa Rica!

**Comment by G6EJD** [comment]
Understood, as I mentioned on YT, you need to programme for those sensors all going off at some stage together, then how do you handle that. It may take many many hours but is likely to happen that 2 or more sensors will trigger at the same time.

**Comment by Rob2029** [comment]
I don't fully understand what will happen in that case, in my case I dont mind losing one signal if that is what happen when they trigger at the same time

**Comment by G6EJD** [comment]
Interrupt happens, control is passed to interrupt service routine (ISR) and then in that you need to detect what caused the interrupt was it say pin-1, or 2, you can test it’s state eg high or low, then decide what to do and it what order 2 then 1 or 1 then 2 can’t do them both at once then return from the ISR.

**Comment by Rob2029** [comment]
mmm ok, what will happen if I don't write code to decide what to do, it will be a problem?

**Comment by G6EJD** [comment]
Behaviour is not easy to predict, most likely you will get unpredictable behaviour and cpu crashes. Interrupts are not a trivial subject there are a lot to them.
